#!/usr/bin/env bash
# Mock claude binary for integration tests.
# Outputs valid Claude Code JSON and makes a git commit to simulate work.

# Create a dummy file to simulate work
echo "// generated by task" > "$PWD/generated.ts"
git add -A >/dev/null 2>&1
git commit -m "feat: implement task" --allow-empty-message >/dev/null 2>&1 || true

# Output valid Claude Code JSON result (result field uses \n escape, not literal newline)
printf '{"type":"result","subtype":"success","cost_usd":0.05,"duration_ms":10000,"num_turns":3,"session_id":"test-session","is_error":false,"result":"DONE\\n\\nImplemented the requested changes successfully."}\n'
